version: "3.3"
services:
  peer2profit:
    image: peer2profit/peer2profit_linux:latest
    container_name: peer2profit
    restart: always
    environment:
      - P2P_EMAIL=${P2P_EMAIL}
  tm:
    image: traffmonetizer/cli
    container_name: tm
    restart: always
    command: start accept --token ${TOKEN}
  psclient:
    image: packetstream/psclient:latest
    container_name: psclient
    restart: always
    environment:
      - CID=1hVA
  proxyrack:
    image: proxyrack/pop
    container_name: proxyrack
    restart: always
    environment:
      - api_key=9JWRZE9COSBNUVVCY07YNBDX8CZ3MXN5RJBRHBKU
      - device_name=cloud
